#ifndef MIDICC_H
#define MIDICC_H

#define CC_GAIN 15
#define CC_SAMPLE_PERIOD_ADC 16
#define CC_DELAY_TIME 17
#define CC_DELAY_HEADSPACE 18
#define CC_DELAY_FEEDBACK 19
#define CC_INPUT_MIX 20
#define CC_DELAY_MIX 21
#define CC_VOLUME 22

#define CC_DELAY_HEAD0 60
#define CC_DELAY_HEAD1 61
#define CC_DELAY_HEAD2 62
#define CC_DELAY_HEAD3 63
#define CC_DELAY_HEAD4 64
#define CC_DELAY_HEAD5 65
#define CC_DELAY_HEAD6 66
#define CC_DELAY_HEAD7 67

#define CC_DELAY_HEAD8 68
#define CC_DELAY_HEAD9 69
#define CC_DELAY_HEAD10 70
#define CC_DELAY_HEAD11 71
#define CC_DELAY_HEAD12 72
#define CC_DELAY_HEAD13 73
#define CC_DELAY_HEAD14 74
#define CC_DELAY_HEAD15 75


#define CC_BIT_REDUCTION 48
#define CC_SAMPLE_PERIOD_DAC 49

#define CC_BIT_B0 40
#define CC_BIT_B1 41
#define CC_BIT_B2 42
#define CC_BIT_B3 43
#define CC_BIT_B4 44
#define CC_BIT_B5 45
#define CC_BIT_B6 46
#define CC_BIT_B7 47


#define CC_CUTOFF 50
#define CC_DELAY_CUTOFF 51

#define CC_DELAY_PING_PONG 0
#define CC_DELAY_REVERSE 1
#define CC_DELAY_FILTER_ENABLE 2
#define CC_INPUT_FILTER_ENABLE 3




#endif